# Generated by Django 6.0.3 on 2026-05-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician'), ('cleaner', 'Cleaner'), ('security', 'Security'), ('accountant', 'Accountant'), ('it', 'IT Staff'), ('other', 'Other')], max_length=20)),
                ('shift', models.CharField(choices=[('Morning', 'Morning (6am-2pm)'), ('Afternoon', 'Afternoon (2pm-10pm)'), ('Night', 'Night (10pm-6am)')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joined_data', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department')),
            ],
        ),
    ]
