# Generated by Django 6.0.3 on 2026-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
